### ISSUE TITLE
Object reference exception thrown on Sandcastle Help File Builder project

### ISSUE THREAD

**Issue by pythoulon** [newky2k/VersionChangerAddin#10]
You need the Sandcastle Help FIle Builder (SHFB) extension loaded. 
![image](https://user-images.githubusercontent.com/11643101/61347250-6e26b980-a85c-11e9-95b9-9b20c64f4b7f.png)

Add a SHFB project to the solution. Launch Version Changer. It dies with an Object Reference message window. 
![image](https://user-images.githubusercontent.com/11643101/61347287-a3cba280-a85c-11e9-8479-107d08c23b54.png)

**Comment by newky2k** [comment]
@pythoulon  Thanks for letting me know.  I'll take a look and see what the issue is
