### ISSUE TITLE
Update version in Package.appxmanifest in UWP project of Xamarin.Forms solution

### ISSUE THREAD

**Issue by cbs-cbt** [newky2k/VersionChangerAddin#12]
Hello,
Please add the possibility to update the Package.appxmanifest file of the UWP project included in a Xamarin.Forms solution

**Comment by newky2k** [comment]
@cbs-cbt Sorry for the delay,  I'll see if i can add this in over the weekend

**Comment by newky2k** [comment]
@cbs-cbt  The addin has now been updated(For 2017/2019 and  VS 2022)  so that it will update the package,appxmanifest file  too
