### ISSUE TITLE
Support for VS 2022

### ISSUE THREAD

**Issue by NunoBem** [newky2k/VersionChangerAddin#17]
Used this extension since VS2017 and works great. Now with the update to VS2022, it doesn't work and I don't seem to find a good replacement. Do you @newky2k  and others don't have this need anymore or is a matter of time or there is an alternative that I don't know?

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by faulandcc** [comment]
Hi, I created a branch and updated it myself but I wasn't able to push the branch or create a pull request.
You can download my VS2022 version here from my server: http://files.sofa1.at/github/VersionChanger.vsix

**Comment by NunoBem** [comment]
> Hi, I created a branch and updated it myself but I wasn't able to push the branch or create a pull request. You can download my VS2022 version here from my server: http://files.sofa1.at/github/VersionChanger.vsix

It works great! Thanks @faulandcc!

@faulandcc and @newky2k you should talk 😄

**Comment by newky2k** [comment]
@faulandcc  I can add you as a contributor if you want to create a pull request.  Or you can fork the repo and do a pull-request that way.

**Comment by faulandcc** [comment]
@newky2k  yeah sure, but I only created a VS2022 version which isn't compatible with older VS anymore. I never created/updated a VS extension before. How do you deal with compatibility?

**Comment by newky2k** [comment]
@faulandcc they changed the way extensions work quite a bit so i dont think there is a way to do it other than have another extension for 2022 and above(that seems to be what most have done).  I've got some time off coming up, so i can take a look at more then.

**Comment by faulandcc** [comment]
@newky2k OK, so in this case you can have a look at my solution. Maybe that's arleady what it takes to get the job done. Can you please add me as a contributor so I can upload my branch? Thanks.

**Comment by newky2k** [comment]
@faulandcc Just sent the invite and i'll take a look over the break.

**Comment by faulandcc** [comment]
@newky2k Thanks man, I just pushed my VS2022 branch.

**Comment by newky2k** [comment]
@NunoBem @faulandcc I have just pushed the new VS 2022 version of the Version Changer to the marketplace.  I've uploaded it as a new extension support VS 2022 only(this seems to be the trend).

You can now download and install it from there -> https://marketplace.visualstudio.com/items?itemName=Newky2k.VersionChanger2022
