### ISSUE TITLE
AssamblyInfo file

### ISSUE THREAD

**Issue by pepaferbar** [newky2k/VersionChangerAddin#19]
Hello,
if project contain class with filename AssamblyInfo.cs and method AssemblyVersion addon crash "startindex cannot be larget....."
![Image 3](https://user-images.githubusercontent.com/92395910/149493725-2bca7db9-7154-4cc7-8d7c-d9c3aaceaa96.png)

**Comment by newky2k** [comment]
@pepaferbar can you provide details on why you would do this?  This seems like an unlikely real world scenario as the AssemblyInfo file is a special file specifically for describing the file thats being compiled.  Not something to be used at runtime in this way.

**Comment by pepaferbar** [comment]
Hello,
I fixed as rename file.
I report to you as possible situation.

---------------------------
s pozdravem
Josef Ferbar ,DiS.
+420 737 134 640

**Comment by newky2k** [comment]
I have updated to check the line that includes keywords includes the assembly: too
