### ISSUE TITLE
Version changer does not work anymore voor Visual Basic .Net Framework projects

### ISSUE THREAD

**Issue by simon-1961** [newky2k/VersionChangerAddin#21]
<html>
<body>
<br class="Apple-interchange-newline">

Hello I am using Version Changer for many years and am very pleased with it. 
However up till last week it was working fine, but now it does not update the versions anymore in my Visual Basic projects (.NET Framework). 
I am using Visual Studio Community 2019 version 16.11.10.

Can you tell me why it is not working anymore?
--

</body>
</html>

**Comment by newky2k** [comment]
@simon-1961 We added an addtional check for "assmebly:" in the line to fix another issue, but in VB its "Assembly:" which is why its stopped working.

We've updated the code and will do some testing and push out an Update ASAP.

**Comment by newky2k** [comment]
@simon-1961  Just about to push the changes to the marketplace.  I've added a VB.Net library project to the test samples and it is getting updated.

Sorry for the delay,  hopefully moving forward we'll be a bit quickere
