### ISSUE TITLE
Please add the 

### ISSUE THREAD

**Issue by itessler** [newky2k/VersionChangerAddin#22]
Please add the ability to update the package version as well.

 <PackageVersion>2022.2.17.4</PackageVersion>

**Comment by newky2k** [comment]
@itessler  It turns out we'd already got support for package version but there was a typo that was stopping from updating it.  

We've fixed the typo and will do some testing and add support for the suffixes.

**Comment by itessler** [comment]
Thank you!

Regards,
Ira Tessler
Senior Developer
ConnectMe Voice LLC

**Comment by newky2k** [comment]
@itessler I'm just about to push out an update with a fix for the packageversion issue.  I've tested it with the SDK sample test project and if the packageversion node is in the csproj is will now get updated.  Additionally, if you use a pre-fix it will be updated in the packageversion too.
