### ISSUE TITLE
Add support for version prefix

### ISSUE THREAD

**Issue by norcino** [newky2k/VersionChangerAddin#28]
I cannot use thi very good extension because I don't use the `version` tag, but I use `VersionPrefix`.
I wish there was a flag to choose between the 2, or better the tool could search for `version` and if not found update the other tag.

An extract of my csproj

```
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>
```

**Comment by newky2k** [comment]
@norcino sorry for the delay, i haven;t been getting any notifications from github for some reason.

Let me look into some more

**Comment by newky2k** [comment]
@norcino Thanks for your patience, i've started looking into this

![image](https://github.com/newky2k/VersionChangerAddin/assets/6675766/6dbfbd80-558e-4746-93ce-34a65b6b8b1c)

**Comment by newky2k** [comment]
This has been implemented in the next major version of the VersionChanger
