### ISSUE TITLE
REQUEST:  Remember project selection

### ISSUE THREAD

**Issue by nhustak** [newky2k/VersionChangerAddin#29]
I have most of my libraries as projects in my primary project.  These have their own version numbers.
I would be really great if it could remember the projects that were check from previous runs.

**Comment by newky2k** [comment]
@nhustak I've got some time coming up I'll see if I can add this feature

**Comment by newky2k** [comment]
@nhustak Sorry for the delay but I am realeasing an update shortly that will remember the project state when you update the projects.
