### ISSUE TITLE
new version doesn't work for nuget packages

### ISSUE THREAD

**Issue by pmespace** [newky2k/VersionChangerAddin#31]
The extension used to allow setting versions with only 3 parts, it no longer allows it forcing the 4th part of the version to be set to something thus making the $(PackageVersion) variable in csproj not reflecting the REAL value of the version number.

as an example a version is set as follows
`    <AssemblyVersion>7.6.6.0</AssemblyVersion>`
and $(PackageVersion) is then 7.6.6.0 while with the 2019 version it was possible to not use the 4th part resulting in a version which was compliant with the version indicated in the nuget package (which would be 7.6.6) making manipulate automatically the nuget package impossible

Could you please reinstate the version on 3 parts ?

**Comment by newky2k** [comment]
@pmespace have you tried turning off the revision number on the options tab?  This is designed to turn of the 4th part of the version number specifically across the board.

![Screenshot 2023-11-10 at 09 42 57](https://github.com/newky2k/VersionChangerAddin/assets/6675766/3a57d175-9d5a-4671-901c-0ca753771cd8)

![Screenshot 2023-11-10 at 09 43 09](https://github.com/newky2k/VersionChangerAddin/assets/6675766/f318962a-9706-4464-9029-b9a0b7b0daf4)

Enabling SemVer2.0 forces this option too

**Comment by eMuonTau** [comment]
I didn't notice there is an Options tab too. 😅 I disabled revision but this time tool did not respect Version Update Options.
If revision is enabled it only updates tags that defined in csproj file. But if you disable revision, even if you uncheck FileVersion, it creates a FileVersion tag.

**Comment by newky2k** [comment]
@eMuonTau Yeah that sounds like a bug!!  I'll take a look and see if i can see what is causing it.

**Comment by newky2k** [comment]
@eMuonTau  Found it, it doesn't look related to the "Enable Revision" checkbox, there is a typo in the bindings for some of the Version options which means it wasn't disabling FileVersion anyway.

**Comment by eMuonTau** [comment]
@newky2k Strange, When you enable revision it does not create FileVersion tag. I did a quick look to send a PR but did not notice any typo. I will check your commit to understand it better. Thanks for your efforts

**Comment by pmespace** [comment]
I must admit I downloaded the code and restarted from VS 2019 version to recreate a VS 2022 with all the details because I couldn't see anything @newky2k indicated in his first answer. I did it very quickly so I apologize for it. I will have a look at your last version see if it does it for me.

**Comment by newky2k** [comment]
@pmespace I haven't updated the 2019 version of the extension yet only the 2022 version.  The new screen and settings are only available there currently, though i do plan to update the 2019 version soon.

@eMuonTau @pmespace  version 4.1.0 of the VS 2022 extension should be available shortly

**Comment by newky2k** [comment]
@pmespace  @eMuonTau  4.1.1 is now available for both VS 2019 and VS 2022.

Hopefully these new versions fix your issues.

**Comment by pmespace** [comment]
@newky2k thank you I'm going to give it a look this evening
