### ISSUE TITLE
Package did not load correctly error.

### ISSUE THREAD

**Issue by PhilKochan** [newky2k/VersionChangerAddin#36]
I am using Visual Studio Community 2022 with only two default extensions installed that came with the new install: ML.NET Model Builder 2022 and Live Share 2022.   no other Extensions installed.

I get the error window shown in the attached file and the attached log file is the result.

I tried running VS 2022 as Administrator and not as Administrator, I also tried uninstalling and reinstalling several times and exiting several times in between each with no success.

If we can get this to work, it's worth $40 to us... I can do Venmo or Zelle Pay... or maybe you have a site where people can donate.  I wish VS MarketPlace had a 'donate' button. :)

Thanks for any help!
Dr. Phil Kochan
McCall, Idaho USAds
[dd_VSIXInstaller_20231121130443_7470.log](https://github.com/newky2k/VersionChangerAddin/files/13430565/dd_VSIXInstaller_20231121130443_7470.log)
![Error Message Window](https://github.com/newky2k/VersionChangerAddin/assets/11748060/05ec9143-fecf-42b3-b6b6-9c2007292a54)

**Comment by PhilKochan** [comment]
I could unistall those other two VSI's if you think that might make a difference. :)

**Comment by newky2k** [comment]
@PhilKochan I have just pushed out a new version of the extensions, 4.1.2 can you start by trying to install the latest version of that.

If that fails can you provide some more details about your system, version of Windows etc

**Comment by newky2k** [comment]
@PhilKochan can you confirm which version of Visual Studio 2022 you are using.  From the log it looks like you are running 17.6, which is now a little out of date.  Can i suggest updating visual studio as a starting point.

The issue appears to be in the VS SDK as its returning a null, when it shouldn't.

**Comment by newky2k** [comment]
@PhilKochan can you try this version, its a vsix file wrapped in a zip file.  

As part of the upgrade to version 4.0.0, I inadvertanly updated the VS SDK from 17.0 to 17.7 which coul
d explain why it works for me but is failing for you.  The attached version revers the SDK version back to what it was.  Let me know if this helps. 

[VersionChanger2022_4.1.2.zip](https://github.com/newky2k/VersionChangerAddin/files/13431071/VersionChanger2022_4.1.2.zip)

**Comment by PhilKochan** [comment]
I updated and it’s working .:)

Thanks!

Do you have a Venmo or Zelle account? 😊

Thanks,
Phil

**Comment by PhilKochan** [comment]
Updating VS worked!  I didn't even have to reinstall.

**Comment by newky2k** [comment]
@PhilKochan thats great new, glad it worked!  We dont have either of those in the UK, but its no problem.
