### ISSUE TITLE
Extension causes VS to crash

### ISSUE THREAD

**Issue by DanAvni** [newky2k/VersionChangerAddin#39]
Using VS2022 17.8.2, I open the extension (version 4.1.2) and close the window when it shows. This causes VS to hang for a long time and then VS2022 crashes.

**Comment by newky2k** [comment]
@DanAvni  I'll take a look tonight, sound like its related to stored the selection state of the projects which is updated when the window is closed(i think).

Has this been fine uptil now and is only happening since updating VS?

**Comment by DanAvni** [comment]
I am not sure when the extension was updated on my machine (set to auto-update) but when I used it a few weeks ago it was ok.

**Comment by newky2k** [comment]
@DanAvni Looking at what happens when you close the window, it is now updated the selection state of the projects and storing the result in the visual studio settings manager.  I'm running 17.8.3 and im not able to replicate the issue.

Do you have a lot of projects loaded?

4.1.2 was released 3 weeks ago so you may have been using it for a while.

**Comment by DanAvni** [comment]
I have about 70 projects in the solution. Maybe instead of storing this in the VS Settings Manager you should store it alongside the solution file. That way it can be committed to git as well.

**Comment by newky2k** [comment]
@DanAvni yeah possibly, though i'd prefer not to introduce files into people repo's unnecessarily.  Let me try it on a larger repo that i have with a similar number of projects.  I might move it to the Update button instead of on close.

**Comment by DanAvni** [comment]
I think adding an option to save is the correct way to go and not doing it behind the scenes (possibly without the user knowledge)

**Comment by newky2k** [comment]
@DanAvni  I've just pushed out an update with an option to "Disable" store of the selection state if its causing an issue as well as some updates to the saving and loading logic for selection state too.  I tried it with 62 .NET 8 projects and couldn't replicate the locking and crashing that you we're seeing.  Hopefully the changes i've made will fixed and if no you can at least disable it now.

**Comment by DanAvni** [comment]
Works great. Thanks!
