### ISSUE TITLE
version 2.2.0 shows no projects in vs 2019

### ISSUE THREAD

**Issue by laureysruben** [newky2k/VersionChangerAddin#8]
Since the 2.2.0 update no projects appear in the list for vs2019 (haven't checked any other versions), rendering the plugin completely useless at the moment.

I assume this has something to do with the new filtering functionality?

**Comment by newky2k** [comment]
@laureysruben what type of projects are you using?

Sorry about this

**Comment by newky2k** [comment]
@laureysruben  do you get any errors at the top?

**Comment by laureysruben** [comment]
Hi,

I realize I did not give that much info :) Just to be clear, this was what we where seeing:

![image](https://user-images.githubusercontent.com/3584297/59011312-8dc9cb80-8834-11e9-8e79-bf1cb7ce778a.png)

I now installed your latest update, and it seems better (thank you!). However, I've got an issue with 1 project still:

![image](https://user-images.githubusercontent.com/3584297/59011529-53146300-8835-11e9-8284-5817b5bcc124.png)

When I hover over the error, it says a project has no assemblyinfo.cs file. This is true, because this project is a office app type project which has a manifest file instead of assemblyinfo file.

I would suggest that if you find projects without assemblyinfo, you'd still show the list but warn about this project? Now all we can do is unload the project to make it work.

**Comment by newky2k** [comment]
@laureysruben  right now the addin support old style csproj files that use assemblyinfo.cs file and new style sdk projects that either have the version details in the csproj file or that use assemblyinfo.  On top of that it will process xamarin.android and ios files, but it uses the combination of those files to read and write the version numbers, thats why its reporting that it couldn't load that project.

Having said all of that there is nothing to stop us adding support for office addins, or even visual studio addins.  If you could provide a test project and some details of the structure of the project(where the version numbers are stored for example) then we should be able to add in support for that type of project.

Alternatively you can add support yourself and create a pull request so we can merge the changes in.

Thanks for you time
